# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: Supermodel-8
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: Supermodel-8
    type: PairedImageDataset
    dataroot_gt: ./datasets/Supermodel/train/sharp_8.txt
    dataroot_lq: ./datasets/Supermodel/train/blur_8.txt

    filename_tmpl: '{}'
    io_backend:
      type: txt

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Supermodel-8
    type: PairedImageDataset
    dataroot_gt: ./datasets/Supermodel/val/sharp_8.txt
    dataroot_lq: ./datasets/Supermodel/val/blur_8.txt

    io_backend:
      type: txt

    gt_size: 256

network_g1:
  type: NLOSLocal
  width: 64
  enc_blk: [64, 128, 256, 512, 512, 512]
  dec_blk: [64, 128, 256, 512, 512, 512]

network_g2:
  type: NLOSStyleLocal
  width: 64
  enc_blk_re: [64, 128, 256, 512, 512, 512]
  enc_blk_de: [128, 256, 512, 512, 512, 512]
  dec_blk: [64, 128, 256, 512, 512, 512]
  num_embeddings: 8
  embedding_dim: 2048
  beta: 0.25
  temperature: 0.1

# path
path:
  pretrain_network_g1: ./NLOS-LTM/step1/experiments/Supermodel-OT-step1/models/net_g_54390.pth
  strict_load_g2: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 240000
    eta_min: !!float 1e-7

  total_iter: 240000
  warmup_iter: -1 # no warm up
  display_freq: 550

# validation settings
val:
  #val_freq: !!float 2e4
  save_img: False
  max_minibatch: 8
  display_freq: 50


  metrics:
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 8000
  save_checkpoint_freq: 4000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# visdom settings
visdom:
  display_winsize: 256
  display_id: 1
  display_port: 8007
  display_single_pane_ncols: 0
  no_html: false

# dist training settings
dist_params:
  backend: nccl
  port: 29500